[package]
name = "ids-combinations"
version = "0.1.0"
edition = "2021"
description = "Script for generating ids combinations"
license = "MIT"

[profile.release]
lto = true
opt-level = 3

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
